server:
  port: 8083

spring:
  application:
    name: order-service


  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/orders_db"
    username: root
    password: root

  cloud:
    config:
      uri: http://localhost:8888

  jpa:
    show-sql : true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  zipkin:
    base-url: http://127.0.0.1:9411/